version: "3.9"

networks:
  default:

services:
  db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: wsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ~/Documents:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d wsdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  app:
    build: .
    depends_on:
      - db
    image: ws-api
    ports:
      - "8080:8080"
      - "587:587"
    links:
      - db
    environment:
      HOST: db
      SPRING_PROFILES_ACTIVE: local
      SPRING_MAIL_HOST: mail.dev.writethis.com.ua
      SPRING_MAIL_PASSWORD: <password>
      SPRING_MAIL_PORT: 587
