spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect