spring:
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:5432/wsdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    servlet:
      multipart:
        max-file-size: 5MB
  mail:
    host: <host>
    port: 0000
    username: system@${wsapi.domain.root}
    password: <password>
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
        required: true

server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: ${wsapi.config.api-version}

logging:
  level:
    root: info

wsapi:
  config:
    api-version: /v1
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    tokenPrefix: "Bearer "
    tokenExpirationDays: 7
  domain:
    root: writethis.com.ua
  emailVerification:
    token:
      expirationMinutes: 15
    redirectUrl: http://localhost:3000
  host:
    protocol: https
    address: ${wsapi.host.protocol}://api.${wsapi.domain.root}/v1
