spring:
  datasource:
    url: jdbc:${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

wsapi:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:https://dev.writethis.com.ua}