spring:
  datasource:
    url: jdbc:${DATABASE_URL}

wsapi:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:https://dev.writethis.com.ua}
  host:
    protocol: https
    address: ${wsapi.host.protocol}://api.dev.writethis.com.ua/v1
